name: Event Proposal
description: Propose an event (talk, workshop or webinar) for ALiAS.
assignees:
  - ditsuke
labels:
  - "type/proposal"
title: "[Proposal] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose an event for [ALiAS](https://asetalias.in)!
        Please fill this form below to help us know about the event and plan it with you.
  - id: EventType
    type: dropdown
    validations:
      required: true
    attributes:
      label: Type
      description: Type of the event
      multiple: false
      options:
        - Talk
        - Workshop / Hands-on
  - id: EventLocation
    type: dropdown
    attributes:
      label: Location
      description: Possible location of the event. You may select multiple options.
      multiple: true
      options:
        - "Campus: Noida"
        - "Campus: Lucknow"
        - "Online (Discord, YouTube Stream or Zoom/Jitsi)"
  - id: EventAbout
    type: textarea
    validations:
      required: true
    attributes:
      label: About
      description: About the event
      placeholder: Something about the event...
  - id: EventPrerequisites
    type: textarea
    validations:
      required: false
    attributes:
      label: Pre-requisites
      description: Pre-requisite requirements or recommenendations for attendees of the event
      placeholder: Hat of wisdom?
  - id: EventDuration
    type: input
    validations:
      required: true
    attributes:
      label: Duration
      description: An estimate for the expected duration of the event
      placeholder: 1-2 hours
  - type: dropdown
    id: EventAudience
    validations:
      required: false
    attributes:
      label: Level
      description: Technical level of the target audience
      multiple: false
      options:
        - "Beginner"
        - "Intermediate"
        - "Advanced"
  - id: EventResources
    type: textarea
    validations:
      required: false
    attributes:
      label: Resources
      description: Resources on the event's topic
  - id: EventSpeakerBio
    type: textarea
    validations:
      required: false
    attributes:
      label: Speakers
      description: >
        About the Speaker(s) of the Event. Ideally, include
        social links (Twitter, LinkedIn, etc).
      placeholder: SpeakerX is a...
